version: '3.8'
services:
  pdb:
    image: postgres:16.2
    container_name: kiut-accounting-db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - pdb
    volumes:
      - ./app:/code/app  # Монтируем локальную директорию с исходным кодом в контейнер
      - files-media-volume:/code/app/media/files/
    command: bash -c "alembic upgrade head && uvicorn app.main:app --reload --host 0.0.0.0 --port 8000"

volumes:
  pgdata: 
  files-media-volume: